package App::WargamersPledge::Model::API;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'App::WargamersPledge::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:wgpledge',
        user => 'root',
        password => '',
    }
);

=head1 NAME

App::WargamersPledge::Model::API - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<App::WargamersPledge>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<App::WargamersPledge::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Mike Whitaker

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
